FROM golang:1.23.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download
COPY . .

RUN go build -o server ./cmd/server/main.go

FROM alpine:latest

ENV RABBITMQ_URL amqp://guest:guest@rabbitmq:5672/

WORKDIR /app

COPY --from=builder /app/server .

CMD ["sh", "-c", "sleep 10 && ./server"]
